name: build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: find . -name go.mod -execdir go get \;

      - name: Test
        run: find . -name go.mod -execdir go test -race -coverprofile=coverage.txt -covermode=atomic \;

      - name: Benchmark with race detector
        run: find . -name go.mod -execdir go test -race -benchmem -bench . \;

      - name: Benchmark
        run: find . -name go.mod -execdir go test -benchmem -bench . \;

      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
