name: golangci-lint
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: find . -name go.mod -execdir go get \;

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2